### ISSUE TITLE
Having issues adding a framework to starter code

### ISSUE THREAD

**Issue by isabelle-chong** [onshape-public/app-gltf-viewer#16]
I’m trying to add a local jquery min file to the starter code via the rollup config file, but keep getting a “module not found” error in the version of the jquery file that gets rolled into the heroku app. Did anyone else try something similar or get a similar problem?

**Comment by ron-onshape** [comment]
You shouldn't need to make changes to the rollup config file for this. If you install jquery through npm and then build with rollup, it should work as expected.

**Comment by isabelle-chong** [comment]
Just to confirm, if I install the jquery through npm basically I don't need to include the jquery.min file in the index.html? Because I installed it using `npm install jquery --save` in the directory I saved the starter code project in, but still get the module not found error for the jquery.min file I have in the index.html

**Comment by ron-onshape** [comment]
No, you don't need it in your index.html. You can include your code in index.js, you just need to import jquery at the top:
```javascript
import ...;
import $ from 'jquery';
...
$(() => alert('jquery is OK'));
...
```

This gets bundled into main.js, which is referenced in index.html.

**Comment by ron-onshape** [comment]
It appears that this is now working for you, so I will close this issue. If you run into any other problems, feel free to open a new issue.
